### ISSUE TITLE
incorrect EC mapping for yeast GO:0008137	NADH dehydrogenase (ubiquinone) activity

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1164]
pombe protein   O94500 and possibly other yeast proteins are asssigned the EC number
EC:1.6.5.3 and the GO mapping
GO:0008137

This is incorrect (as far as I'm aware for all yeast, but definitely for pombe and cerevisiae).

This is a conserved  protein, which is present in mitochondiral respiratory complex I in mammals, but neither pombe or cerevisiae have complex I. This activity
    (NADH dehydrogenase (ubiquinone) activity) is provided by an unrelated protein

(the mammalian complex has ~44 sunits and pombe and cereviaiae onyl have 2 of these which likely have a   more general role in protein complex assembly)

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1180](https://sourceforge.net/p/geneontology/annotation-issues/1180)

**Comment by hdrabkin** [comment]
Hi @ValWood 
"Sent to UniProt" 
Was this fixed by UniProt?

**Comment by ValWood** [comment]
http://www.uniprot.org/uniprot/O94500

It now has 
(EC:1.6.-.-Curated)
which is also incorrect.

This is  a subunit of the NADH complex I in human, but it DOES NOT have oxidoreductase activity. It just happens to be a member of a very large ~45 member) complex I in human. 
The oxidoreductase activity does not reside in this subunit, it has only been *isolated* in combination with complexI.

**Comment by hdrabkin** [comment]
This is why we removed EC.x.y.- from dbxrefs for GO terms. 
I would have thought a curated record would have a better than 'class' ec number. 
I can take a look to see what EC:1.6.- is mapped to for a go term

**Comment by ValWood** [comment]
OK, you can close. It shouldn't have the EC number, but not a problem if there is no mapping.

**Comment by pgaudet** [comment]
@kaxelsen 
It seems like the EC mapping is still incorrect; can you please have a look ? 

Thanks, Pascale
