### ISSUE TITLE
matrix human SMC1A not splicing

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1375]
Human SMC1a is annotated to 

mRNA splicing, via spliceosome
Reactome TAS. Can this be deleted, It doesn't  have a role in splicing AFAIK

(I 'll   put this one through protein2GO, but I don't think the  Reactome mapping issues I have reported so far are getting fixed. I want this one as an example to link to another ticket).

Val

**Comment by ValWood** [comment]
Oddly I do not see this annotation in protein2GO,
although I see it in the GO database attached to this Uniprot entry:
http://amigo.geneontology.org/amigo/gene_product/UniProtKB:Q14683

Why   are there different entries for SMC1A with different annotations attached?

**Comment by cmungall** [comment]
I can't see protein2go, but QuickGO, AmiGO and the GAFs appear to be consistent. I assume because Reactomes are imported it can't be edited in p2go?

I'm having a hard time finding this in a splicing pathway in Reactome, cc @deustp01

**Comment by ValWood** [comment]
Well I see *some * Reactome annotation in protein2GO, just not ALL of them. So I can't figure out  what the criteria is for Reactome annotation to be included in Protein2GO.
Usually I would raise a dispute this way.

**Comment by ValWood** [comment]
This could be a bigger problem....

http://jira.geneontology.org/browse/GO-1147?jql=project%20%3D%20%22GO%22%20AND%20created%3E%3D-1w%20ORDER%20BY%20created%20DESC

**Comment by deustp01** [comment]
I can't get to the URL to see the "bigger problem" but here are some comments about the problem in the rest of the thread. But if 

How did we generate the assertion that SMC1A has a role in "mRNA splicing, via spliceosome"? Like Val and Chris, I can't figure out how we made that specific mistake.

However, until very recently, we generated many protein-to-biological_process assertions by taking a high-level Reactome pathway, like "mRNA splicing" or, worse, "gene expression", grabbing the list of all the proteins associated with any aspect of that pathway, and writing GAF lines that associating every one of those proteins with the biological_process term we have assigned to the high-level pathway. Often that's harmless - lots of enzymes get assigned (correctly) to "carbohydrate metabolism" or "EGFR signaling". Other times, as here, it's not.

The fix is to change our procedure for assigning biological_process terms to proteins. In the latest version of our script to extract GAF lines from Reactome annotation, our event hierarchy is traversed bottom-up (instead of top-down, as previously). So the script starts with a single-step reaction and asks if a biological_process term has been assigned to that reaction. If so, it associates that term with any proteins associated with the reaction, and goes on the the next reaction. If not, the script looks for the sub-sub-pathway that the reaction is part_of. If the sub-sub-pathway has a biological_process term, that term is used for the reaction's proteins, and the script then moves on to the next reaction. Otherwise it looks for the parent sub-pathway, and so on.

The GAF that we just submitted in connection with our March 2016 release is, I hope, the first to use this new strategy. It should help a lot.

Now, two more questions. Why are there unexpected gaps in Reactome annotations in protein2GO? Because many of our annotations don't parse into something that makes a legal GAF line and so far finding these and looking for ways to fix them has been a low priority at Reactome (there is a permanent thundercloud over the Reactome entry in Jenkins). We are trying to improve that. [Insert standard verbiage about scarce resources here.]

Second, why are there UniProt - protein2GO - Reactome discrepancies? Basically, though we feed updated information to UniProt with every quarterly release, there have been delays and irregularities in getting this information processed and visible on UniProt protein pages. Even here, my information is incomplete - most discussion has been about getting new annotations propagated to UniProt faster, but now that I think about it, I'm not sure there even is a mechanism to ensure that if we deprecate an annotation, it disappears from the GO annotation section of the UniProt page.

**Comment by ValWood** [comment]
Don't worry about the 'bigger problem' Peter. That was me going off on a  tangent. 

However, my tangent was based an an assumption that some legacy annotations were hanging around, and that might be the case for Reactome  from what you say here (I thought initially that other pipelines could also be affected).

So I guess that the action  of this thread is to ensure somehow that legacy annotations are purged?
Don't GO  and GOA reload Reactome a fully from scratch? The annotations I referred to were not present in Protein2GO (although I could see other Reactome TAS entries), but they were present in GO.

**Comment by cmungall** [comment]
Just to clarify for anyone else coming to this thread, we're talking about `assigned_by=Reactome` lines within the GOA GAF, rather than issues with the Reactome GAF (which we're not currently loading in AmiGO). The current reactome GAF does *not* have this annotation.

So it sounds like these oddities were a result of the old Reactome pipeline. GOA pulls in Reactome, so somehow these are not being purged in GOA, so they are sticking around in the GAF. @tonysawfordebi any idea what is up?

**Comment by ValWood** [comment]
Ah yes my mistake. Even though they aren't in Protein2GO, they are in GOA
http://www.ebi.ac.uk/QuickGO/GProtein?ac=Q14683

**Comment by ValWood** [comment]
@deustp01  Are the "protein sumoylation/post-translational protein modification" annotations also extant ? They don't seem quite right for SMC1A either?

**Comment by ValWood** [comment]
It would be nice to reduce the redundancy from the Reactome pipeline.

For this single gene product:
nucleoplasm 15 TAS
chromosome 4 TAS
cytosol 4 TAS
chromosome, centromeric region 5 TAS

**Comment by mcourtot** [comment]
As mentioned on the helpdesk ticket, and after checking with @tonysawfordebi:

The last GOA release was March 14th 2016, and as mentioned by Chris the GOA files produced at this time include those annotations. The latest snapshot we still have of the Reactome file is dated March 29th, and does not include those annotations. It therefore seems that those annotations were deleted from Reactome between March 14th and March 29th. 

Taken with this GitHub ticket, we further know these were deleted between March 27th and March 29th, and the difference seen between P2GO and QuickGO is a timing issue which should be solved when QuickGO finishes loading the files somewhere late afternoon today.

**Comment by deustp01** [comment]
That's plausible - Reactome got out a new release on March 24 (version 56), and while our annotations for SMC1A shouldn't have changed from version 55 (December 2015 - need to double-check this), our procedure for assigning biological_process terms should have changed as described in the long comment yesterday.
So, to-do items now on the Reactome side: confirm the state of our SMC1A annotations, and examine all GAF lines for SMC1A to see if we have now eliminated unwanted biological_process annotations and to figure out why / whether we're generating redundant cell_component annotations (Val's most recent comment).

**Comment by ValWood** [comment]
mRNA splicing, via spliceosome
is gone for SMC1A so will close

protein sumoylation is still present in Uniprot, but absent from QuickGO?
I guess thats a time lag, but there is another ticet about that mapping I think...
