### ISSUE TITLE
PTN000941828 (PTHR11941)

### ISSUE THREAD

**Issue by phanivg** [geneontology/go-annotation#1883]
Please review the PAINT (PANTHER:PTN000941828) inference for Dmel HIPP1 (FBgn0037027): 
GO:0004300 enoyl-CoA hydratase activity" annotation was assigned to D.mel HIPP1 (UniProt:Q9VPB0, M9PG20, M9PID3, M9PG82) based on human "Enoyl-CoA hydratase, mitochondrial" and "Methylglutaconyl-CoA hydratase, mitochondrial", which have no obvious orthology relationship to Dmel HIPP1. 
@hattrill

**Comment by sjm41** [comment]
Can we look into this one please - dates from nearly 3 years ago!

I had made a similar ticket on the Panther tracker (https://github.com/pantherdb/Helpdesk/issues/14), but I'm going to close that and copy the info onto this ticket.

**Comment by sjm41** [comment]
PTN000941828 adds "enoyl-CoA hydratase activity" and "fatty acid beta-oxidation" to all genes under PTHR11941.

PTHR11941 currently contains (examples):

These 5 human genes:
ECHS1 (P30084) = Enoyl-CoA hydratase
ECHDC2 (Q86YB7) = Enoyl-CoA hydratase
AUH (Q13825) = Methylglutaconyl-CoA hydratase
ECI1 (P42126) = Enoyl-CoA delta isomerase
ECHD1 (Q9NTX5) = Ethylmalonyl-CoA decarboxylase

and these 6 fly genes:
Echs1 (Q7JR58) = ECHS1 ortholog => hydratase
CG8778 (A1Z934) = AUH ortholog => hydratase
CG4592 (Q9VL66) = ECI1 ortholog => isomerase
CG4594 (Q9VL67) = ECI1 ortholog => isomerase
CG4598 (Q9VL68) = ECI1 ortholog => isomerase
HIPP1 (Q9VPB0) = [no clear ortholog], characterized in flies as a chromatin-associated protein

All the fly genes (at least) have this InterPro domain:
Enoyl-CoA hydratase/isomerase (IPR001753)
http://www.ebi.ac.uk/interpro/entry/InterPro/IPR001753/
which says that this family "contains a diverse set of enzymes including: enoyl-CoA hydratase, 1,4-dihydroxy-2-naphthoyl-CoA synthase (napthoate synthase), carnitinyl-CoA dehydratase (carnitine racemase), 3-hydroxybutyryl-CoA dehydratase and enoyl-CoA delta isomerase"

So it's not appropriate to propagate "enoyl-CoA hydratase activity" to all current family members.

**Comment by pgaudet** [comment]
Fixed. Thanks for your patience ;)

**Comment by sjm41** [comment]
wonderful, thanks!

**Comment by sjm41** [comment]
Hi @pgaudet 

I just came across some of the issues described in this ticket again.  Looks like the problem described in the first post of this ticket has been fixed (i.e. HIPP1/FBgn0037027 no longer has "GO:0004300 enoyl-CoA hydratase activity" from PTN000941828), but the wider issue mentioned further down still exists.  That is, the following isomerases are still getting "enoyl-CoA hydratase activity" from PTN000941828:
human ECI1 (P42126) = Enoyl-CoA delta isomerase
fly CG4592 (Q9VL66) = ECI1 ortholog
fly CG4594 (Q9VL67) = ECI1 ortholog
fly CG4598 (Q9VL68) = ECI1 ortholog

**Comment by sjm41** [comment]
Hi @pgaudet/@marcfeuermann  Can you remove "enoyl-CoA hydratase activity" from PTN000941828 ? Or else split the family to give appropriate annotations with 'hydratase' (lyase) and 'isomerase' activities? Thanks.

**Comment by sjm41** [comment]
Giving this one another nudge....

**Comment by marcfeuermann** [comment]
Finally updated :-)

**Comment by sjm41** [comment]
Thanks Marc!
