### ISSUE TITLE
PTN000559990 (PTHR23105)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1952]
from
https://github.com/geneontology/go-annotation/issues/1873
This one is very bizarre, I can't work it out.

Pombe Tos4 is a FHA domain protein.
The S. cerevisiae ortholog is  Tos4
https://www.yeastgenome.org/locus/YLR183C   Q06266

However the PAINT family references unrelated proteins ?

http://www.pantree.org/node/annotationNode.jsp?id=PTN000559990

ribosomal protein
http://www.uniprot.org/uniprot/P29453

**Comment by ValWood** [comment]
Fixed @pgaudet  put some NOTs and reported to @huaiyumi

**Comment by ValWood** [comment]
pombase: SPAP14E8.02 and SGD:S000004173
should not be there.

**Comment by thomaspd** [comment]
I agree, @huaiyumi for some reason there are tos4 homologs from many fungi, including yeast and pombe, in PTHR23105 (a ribosomal protein family) in various places.  But they align really badly and clearly don't belong in the family.  Can you please remove them from the tree in the next version of PANTHER, and make a new family with these sequences (plus some others in some other fungi that aren't currently in a family, just search PANTHER for tos4).

**Comment by pgaudet** [comment]
I dont think the tree has changed - TOS4 (S000004173) is still present.

**Comment by pgaudet** [comment]
@huaiyumi @thomaspd Can we move tree issues elsewhere ?

**Comment by pgaudet** [comment]
Opened Panther ticket: https://github.com/pantherdb/Helpdesk/issues/9
