### ISSUE TITLE
IBA	PANTHER:PTN000815317

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2135]
photorespiration |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000815317UniProtKB:Q944I4 | uridine kinase pthr10285 | protein |   | PMID:21873635 | 20170228

needs removing.

**Comment by pgaudet** [comment]
@ValWood next time plus provide the Pombase ID. How do I know what to look at? 
Can you check if this (and others) were fixed in the release that just came out Friday ?

**Comment by ValWood** [comment]
That's weird, I'm cutting and pasting the row from AmiGO. Do none of these contain the pombe ID?

**Comment by ValWood** [comment]
first two rows missed

mug58 | GLYK family kinase of unknown specificity, implicated in nucleotide metabolism (predicted)


I can check  this one and any other the taxon ones on Friday, but all of the others are completely new, so there is no reason why they would be fixed already? I'll spot check a few but I would assume there is still a problem with these.

**Comment by pgaudet** [comment]
OK thanks, I'll have a look, I wasn't sure.

**Comment by ValWood** [comment]
I checked as I submitted the IDs. The only duplicate was
https://github.com/geneontology/go-annotation/issues/2167
but I included these as at the time I thought  the fix should have come through.

**Comment by pgaudet** [comment]
Fixed.
