### ISSUE TITLE
PAINT annotation of PGRP (PTHR11022)

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2559]
Could you please block and reassess the annotations propgated from 
PTN001664863
PTN001664864
PTN001336553

I've got a couple of tickets open on some of these nodes  #2555 and #2558 which has prompted me to look at the Peptidoglycan Recognition Proteins. I shall roll these up into this ticket and close those.

Note: I can't see the Tree node information so it's hard for me to dig properly (get "Unable to retrieve family information at this time for null" when following the linkout)

So.....PGRP across species can act in a variety of different ways: some are receptors, some have amidase function, some are peptidoglycan receptors, some are secreted, some are transmembrane and some are even intracellular; some are part of immune response signaling pathways, some positively or negatively regulate these pathways. 

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3412580/
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1779587/

In short, the variety of activities associated with these related proteins makes it hard to PAINT.

For D.mel all of our PGRPs and one that is not a PGRP have annotations propagated from three nodes:

PTN001664863
peptidoglycan binding  
extracellular space

PTN001664864
peptidoglycan receptor activity
N-acetylmuramoyl-L-alanine amidase activity

PTN001336553
defense response to Gram-positive bacterium
negative regulation of natural killer cell differentiation involved in immune response
antimicrobial humoral response

but they do not all have these activities/locations and some activities are directly in conflict e.g. N-acetylmuramoyl-L-alanine amidase activity and peptidoglycan receptor activity

ID | SYMBOL | Pathway | CC | MF
FBgn0035975 | PGRP-LA | Imd | Transmembrane | not binding or catalytic
FBgn0037906 | PGRP-LB | Imd | extracellular | amidase
FBgn0035976 | PGRP-LC | Imd/PO | Transmembrane | binding
FBgn0260458 | PGRP-LD | ? | Transmembrane | not catalytic
FBgn0030695 | PGRP-LE | Imd/PO | intracellular or extracellular | binding
FBgn0035977 | PGRP-LF | Imd (neg reg) | Transmembrane | not binding or catalytic
FBgn0030310 | PGRP-SA | Tl | extracellular | binding
FBgn0043578 | PGRP-SB1 | Tl | extracellular | amidase
FBgn0043577 | PGRP-SB2 | Imd | extracellular | amidase
FBgn0043576 | PGRP-SC1a | Tl/Imd | extracellular | amidase
FBgn0033327 | PGRP-SC1b | Tl/Imd | extracellular | amidase
FBgn0043575 | PGRP-SC2 | Tl/Imd | extracellular | amidase
FBgn0035806 | PGRP-SD | Tl/Imd | extracellular | binding
FBgn0035094 | CG9380 | Don't think that this is a genuine PGRP - no significant alignment with   d.mel PGRP - has a domain, but only PANTHER orthogy tool picks up this.

negative regulation of natural killer cell differentiation involved in immune response - is a) too specific and b) vertebrate-specific
and
there are some odd choices given the number of experimental annotations available:
"defense response to Gram-positive bacterium" seems odd to choose as gram-neg response must also be heavily annotated? As does "extracellular space" as there are plenty of int. to plasma membranes.
(Fixing the NOT issue would also help with the enzyme activity)

Immune processes are very divergent across species - this is a good example of where some background in the subject and some logic checks would help.

I am in the process of cleaning up any spurious annotations that come from non-IBA sources.

**Comment by pgaudet** [comment]
@hattrill 
You get an ''Unable to retrieve family information at this time for null" when following the linkout'' -> from where ? AmiGO ? 

I was looking at the IBAs for FBgn0035975 and again we dont see the family ID in AmiGO- I thought this was resolved @dustine32 @kltm ?

**Comment by hattrill** [comment]
I can still see them in http://amigo.geneontology.org/amigo/search/annotation?q=FB:FBgn0035975
but they may have fixed them in PAINT, but I have no indication of that.

Node tree seems to be working today:
http://www.pantree.org/node/annotationNode.jsp?id=PTN001664864
went to coorect page with no error.

**Comment by pgaudet** [comment]
I meant, the PANTHER family column is empty
![image](https://user-images.githubusercontent.com/4782928/61368679-b363df00-a88e-11e9-89db-775c6f4f67f9.png)

**Comment by hattrill** [comment]
So it is - the link is in the IBA "with":
![Screenshot 2019-07-17 at 11 40 43](https://user-images.githubusercontent.com/11865746/61369363-d76ff200-a887-11e9-92a0-0dedd27578c3.png)

**Comment by pgaudet** [comment]
Right - there *is* a link to Pantree. 
However the PTHRID should be in this table. I think @dustine32 and @kltm know what I mean; I reported this before. 

Pascale

**Comment by dustine32** [comment]
@pgaudet Yeah those Panther family columns should be filled in with _something_. Thanks for the examples. I'll track down the reason.

**Comment by dustine32** [comment]
@pgaudet @kltm I think this problem is limited to FlyBase (and also likely WormBase) identifiers and is tackled [here](https://github.com/geneontology/amigo/issues/546#).

To illustrate, tracing this GP to its Panther family's tree file used in populating the amigo column, I see the line entry for PGRP-LA's ID `FB:FBgn0035975`:
```
AN204:DROME|FlyBase=FBgn0035975|UniProtKB=Q95T64;
```
It's this discrepancy between `FB:` and `FlyBase=` prefixes causing the mismatch that prevents the family column population. I fixed this problem for `FB:` and `WB:` but only in the tree file generation for 14.1 trees. And amigo (through the release pipeline) is still pulling the 13.1 trees and IBAs. I'm actually hoping to [test](https://github.com/geneontology/pipeline/issues/78) the 14.1 switch on `snapshot` today.

**Comment by kltm** [comment]
@dustine32 Don't we have the FlyBase/FB, WormBase/WB being tracked in another ticket as well?

**Comment by dustine32** [comment]
@kltm Oh right! I guess in the Panther helpdesk too:
https://github.com/pantherdb/Helpdesk/issues/3

**Comment by kltm** [comment]
For GO,
https://github.com/geneontology/go-site/issues/512
https://github.com/geneontology/go-site/issues/685
Others?

**Comment by marcfeuermann** [comment]
The family has been completely reviewed. Only small vertebrate nodes where there are no big duplication patches have been annotated.
