### ISSUE TITLE
PANTHER:PTN000019791 - protein kinase activity(CONTRIBUTES_TO)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2775]
http://www.pantree.org/node/annotationNode.jsp?id=PTN000019791

Propagates "protein kinase activity(CONTRIBUTES_TO) IBD" to a bunch of Cyclin genes/proteins, which is don't think is correct/desired (given the cyclin is the regulatory/specificity subunit, lacking kinase activity itself)

Source annotations for this appear to be:
PTN000020082  (RAT\|RGD=2291\|UniProtKB=P30277)
PTN002468734  (HUMAN\|HGNC=1578\|UniProtKB=P20248)

I've disputed the human one in protein2GO.
@slaulederkind - can you check the rat ones?
kinase activity (ISO) PMID:12124778
histone kinase activity IDA) PMID:16141400
(Maybe use "protein kinase regulator activity" (or a child thereof) instead? )

I believe that if the source annotations go away, then the term automatically gets removed from the IBA annotation.

**Comment by sjm41** [comment]
tagging @hattrill

**Comment by sjm41** [comment]
The annotation to human P20248 has now been changed to "cyclin-dependent protein serine/threonine kinase regulator activity", so that's sorted.

**Comment by slaulederkind** [comment]
Hi Steven, I deleted the manual RGD annotation (histone kinase activity” IDA) PMID:16141400), but the other annotation (kinase activity (ISO) PMID:12124778) is based on a mouse annotation originating at MGI.  Thanks, Stan

**Comment by sjm41** [comment]
Thanks Stan.

@hdrabkin - can you review this MGI annotation please:
P24860 (Ccnb1) to "kinase activity" IDA from PMID:12124778

**Comment by hdrabkin** [comment]
done

**Comment by sjm41** [comment]
Thanks Harold.
@slaulederkind - will the RGD ISO annotation ("kinase activity" to P30277 from PMID:12124778) get updated automatically now the MGI annotation has changed, or will you still need to edit your annotation manually?

**Comment by pgaudet** [comment]
ISO annotations are updated automatically.

**Comment by sjm41** [comment]
@pgaudet - I just checked the rat ISO annotation (mentioned above) in protein2GO, and it's still present even though Harold deleted the source mouse annotation on 22nd Jan.  Is this just a timing/sync-ing issue, or is there a problem?

PTN000019791 still has " protein kinase activity(CONTRIBUTES_TO)" associated with it - maybe be better to manually remove this from the node rather than waiting for the issue with the source annotations to get resolved/filter through?

**Comment by hdrabkin** [comment]
I think it's a sync issue. We release new gaf/gpad daily. RGD may be longer. FYI we have also not seen a change in the file we get from RGD to do our mouse_to_rat iso load.

**Comment by pgaudet** [comment]
From the source files, it looks like the RGD file we have in the release is from 2020/02/15  (see file http://current.geneontology.org/products/annotations/rgd-src.gaf.gz in this folder 
http://current.geneontology.org/products/annotations/index.html

This ISO is still present in their source file. So I suppose the ISO script ran on data that's older than Jan 22. 

@jrsjrs at what frequency is the RGD ISO pipeline ran ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
@sjm41 Sure I'll fix it. It's a 2000-members kinase family, I tried to open it before and got scared !! Time to be brave !

**Comment by sjm41** [comment]
Great, thanks!  (You mean 2000-members **cyclin** family, right?)

**Comment by pgaudet** [comment]
cyclin-dependent PK - isn't it ??

**Comment by sjm41** [comment]
PTN000019791 is for PTHR10177, which is named 'CYCLINS'
http://www.pantherdb.org/panther/family.do?clsAccession=PTHR10177

Just checked the human and fly members, and they are all indeed 'cyclins'.

This is why it would be good to get rid of the 'protein kinase activity' term on the PTN000019791 node, as the family is just for the cyclin subunit (not the kinase (Cdk) subunit).

**Comment by pgaudet** [comment]
Yes apologies, they are cyclins.

**Comment by pgaudet** [comment]
OK fixed. It wasn't so bad after all.

**Comment by sjm41** [comment]
Great, thanks!
