### ISSUE TITLE
Review annotations to "cofactor" grouping terms

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-annotation#2926]
We are planning to obsolete all of the `cofactor` grouping terms, see https://github.com/geneontology/go-ontology/issues/19243 for explanation.

I've included sequence based annotations to make sure the manual sequence annotations are reviewed, though I know some are from loads based on orthology with other sequences. If it will be fixed once the original annotation is fixed, you can just put a comment in the first column.

https://docs.google.com/spreadsheets/d/15aLkDsoScybffpARFmbrZxO0Ki8z7YVU_epgyvBwBjs/edit?usp=sharing

**Direct annotations to `cofactor` terms - Evidence by Contributor**

Contributor | IDA | IMP | IPI | NAS | TAS | ISM | ISO | ISS | Grand Total
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
UniProt | 25 | 4 |   | 1 | 1 |   |   | 23 | 54
Reactome |   |   |   |   | 9 |   |   |   | 9
RGD | 4 | 1 | 2 |   |   |   | 2 |   | 9
GeneDB | 4 |   |   |   |   |   |   |   | 4
EcoCyc | 1 | 2 |   |   |   |   |   |   | 3
SGD | 3 |   |   |   |   |   |   |   | 3
BHF-UCL |   |   | 1 |   |   |   |   |   | 1
CGD | 1 |   |   |   |   |   |   |   | 1
EcoliWiki |   |   | 1 |   |   |   |   |   | 1
PomBase |   |   |   |   |   | 1 |   |   | 1
MGI |   |   |   |   |   |   | 2 |   | 2
AgBase |   |   |   |   |   |   |   | 2 | 2
PseudoCAP |   |   |   |   |   |   |   | 2 | 2
ZFIN |   |   |   |   |   |   |   | 1 | 1
Grand Total | 38 | 7 | 4 | 1 | 10 | 1 | 4 | 28 | 93

**Comment by krchristie** [comment]
MGI's two ISO's will be fixed when the source human annotations to PPT1 are fixed.

**Comment by keseler** [comment]
Hi @krchristie,
Could you give me access to the spreadsheet?  Don't know how to make that work, but I currently can't get to it.
Hope you're well!
Cheers,
Ingrid

**Comment by krchristie** [comment]
> Hi @krchristie,
> Could you give me access to the spreadsheet? Don't know how to make that work, but I currently can't get to it.
> Hope you're well!
> Cheers,
> Ingrid

My bad! I haven't created that many of these annotation spreadsheets. I updated the link in the original comment to be the sharable link. Hopefully that works now, but let me know if you still have problems.

Hope you're well too!
Best, Karen

**Comment by keseler** [comment]
No worries!  I learned how difficult it can be to do "old" things, much less learn/remember how to do new things, when working from home...
Now I was able to see the spreadsheet, but not edit it.  It's only three proteins, so no big deal; I fixed all three in the current beta version of EcoCyc (which should trickle down to the GO eventually).

**Comment by krchristie** [comment]
I don't know what happened with the original spreadsheet. Somehow I marked it view only, and now I can't edit it either. I started over with another copy of the template and replaced the link in the original comment. I can't blame this on working from home though. I always work from home, and my boss gets us laptops so that even we travel, we still have the same setup. Thanks for fixing so quickly! @keseler

**Comment by RLovering** [comment]
UCL annotation changed

**Comment by Achchuthan** [comment]
@uliboehme will review the four Plasmodium annotations at GeneDB and will update the spreadsheet.

**Comment by uliboehme** [comment]
Annotation for PF3D7_0815900 and PF3D7_1232200 have been changed in the Artemis annotation database. I don't have access to the UniProt annotations (Q8I5A0, Q8IAZ6). This needs to be changed by UniProt.

**Comment by pgaudet** [comment]
Hi @uliboehme 
In fact those are duplicate. The issue is that in the genedb yaml file (https://github.com/geneontology/go-site/blob/master/metadata/datasets/genedb.yaml) you have NCBITaxon:5833, but you submit NCBITaxon:36329. We don't take into account children of the taxon. 

I'll add NCBITaxon:36329 to your yaml file. That should prevent the same annotations to also be uploaded from the UniProt file. 

@kltm Do I need to do anything else ? 

Thanks, Pascale

**Comment by uliboehme** [comment]
Hi @pgaudet, 
Thanks for looking into this issue.

**Comment by marekskrzypek** [comment]
CGD's one item has been removed

**Comment by kltm** [comment]
@pgaudet That addition will trigger the removal of that taxon from goa_uniprot_all and mark genedb as the "canonical" resource.

**Comment by krchristie** [comment]
> Hi @uliboehme
> In fact those are duplicate. The issue is that in the genedb yaml file (https://github.com/geneontology/go-site/blob/master/metadata/datasets/genedb.yaml) you have NCBITaxon:5833, but you submit NCBITaxon:36329. We don't take into account children of the taxon.
> 
> I'll add NCBITaxon:36329 to your yaml file. That should prevent the same annotations to also be uploaded from the UniProt file.
> 
> @kltm Do I need to do anything else ?
> 
> Thanks, Pascale

Is it necessary to do anything? If the UniProt ones are being created by their pipeline based on the primary annotation in the Artemis annotation database, then they'll be fixed the next time the pipeline runs based on the fact that the primary annotation has changed. I would suggest putting a note in the first column for now. 

@pgaudet - I think it might be worth have an additional option in the second column "COMMENT (FIXED /OK) - by Contributor" to indicate annotations that will be automatically fixed as they are dependent on a manual annotation via a load. This is the case for most, or all, of the ISO annotations that MGI has and none of the existing options (Changed, Removed, Checked and unchanged) seem correct.

**Comment by pgaudet** [comment]
> Is it necessary to do anything? If the UniProt ones are being created by their pipeline based on the primary annotation in the Artemis annotation database, then they'll be fixed the next time the pipeline runs based on the fact that the primary annotation has changed. I would suggest putting a note in the first column for now.

Yes we need to add the taxon ID in the geneDB file to avoid those duplicates. 

> I think it might be worth have an additional option in the second column "COMMENT (FIXED /OK) - by Contributor"

OK I'll add this to the template, thanks for the feedback.

**Comment by pgarmiri** [comment]
Hi,
All the experimental UniProt annotations have been reviewed. The ISS one will be automatically updated.
Thanks,
Penelope

**Comment by slaulederkind** [comment]
All RGD annotations corrected or removed.

**Comment by pgaudet** [comment]
@krchristie Should I close this ticket ?

**Comment by krchristie** [comment]
If the criteria to close is whether or not the relevant terms have been obsoleted or not, then I suppose it's time. I'll close.
